const data = {
  products: [
    {
      _id: "1",
      name: "ThinkPad X1 Extreme Gen 4",
      category: "Laptop",
      image: "/images/product-1.png",
      price: 2000,
      brand: "ThinkPad",
      rating: 4.5,
      numReviews: 10,
      description: "High quality product",
    },
    {
      _id: "2",
      name: "ThinkPad X1 Extreme Gen 4",
      category: "Laptop",
      image: "/images/product-1.png",
      price: 2000,
      brand: "ThinkPad",
      rating: 4.5,
      numReviews: 10,
      description: "High quality product",
    },
    {
      _id: "3",
      name: "ThinkPad X1 Extreme Gen 4",
      category: "Lenovo",
      image: "/images/product-1.png",
      price: 2000,
      brand: "ThinkPad",
      rating: 4.5,
      numReviews: 10,
      description: "High quality product",
    },
    {
      _id: "4",
      name: "ThinkPad X1 Extreme Gen 4",
      category: "Laptop",
      image: "/images/product-1.png",
      price: 2000,
      brand: "ThinkPad",
      rating: 4.5,
      numReviews: 10,
      description: "High quality product",
    },
    {
      _id: "5",
      name: "ThinkPad X1 Extreme Gen 4",
      category: "Lenovo",
      image: "/images/product-1.png",
      price: 2000,
      brand: "ThinkPad",
      rating: 4.5,
      numReviews: 10,
      description: "High quality product",
    },
    {
      _id: "6",
      name: "ThinkPad X1 Extreme Gen 4",
      category: "Laptop",
      image: "/images/product-1.png",
      price: 2000,
      brand: "ThinkPad",
      rating: 4.5,
      numReviews: 10,
      description: "High quality product",
    },
  ],
};
export default data;
